spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://csj7001:8201/eureka/

---
server:
  port: 8202
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://csj7002:8202/eureka/